version: "3"

tasks:
  default:
    cmds:
      - task: build
      - task: run
  build:
    cmds:
      - zig build .
  run:
    cmds:
      - ./zig-out/passback {{.CLI_ARGS}}
  vhs:
    cmds:
      - vhs ./vhs/passback.tape
