#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# Helper functions start with _ and aren't listed in this script's help menu.
# -----------------------------------------------------------------------------

set -euo pipefail

APP_NAME="$(basename "$(git rev-parse --show-toplevel)")" || APP_NAME="$(basename "$PWD")"
PROJECT_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || PROJECT_ROOT="$PWD"

TTY="${TTY:-}"
if [[ ! -t 1 ]]; then
  TTY="-T"
fi

VERSION="$(cat "$PROJECT_ROOT"/VERSION 2>/dev/null)" || VERSION="dev"

help() {
  echo ""
  echo "-------------------"
  echo " tsk [task] [args] "
  echo "-------------------"
  declare -F | awk '{print "◉ " $3}' | grep -v "◉ _" | sort
}

run() {
  odin run "$PROJECT_ROOT" -define="VERSION=$VERSION" --collection:lib="$PROJECT_ROOT"/lib "$@"
}

debug() {
  odin run "$PROJECT_ROOT" -define="VERSION=$VERSION" -debug --collection:lib="$PROJECT_ROOT"/lib "$@"
}

debug:sanitize() {
  odin run "$PROJECT_ROOT" -define="VERSION=$VERSION" -debug -sanitize:address --collection:lib="$PROJECT_ROOT"/lib "$@"
}

build() {
  odin build "$PROJECT_ROOT" -define="VERSION=$VERSION" -o:speed --collection:lib="$PROJECT_ROOT"/lib -out:"$PROJECT_ROOT"/"$APP_NAME" "$@"
}

vhs() {
  command vhs "$PROJECT_ROOT"/vhs/passback.tape
}

TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"
